### ISSUE TITLE
Not working on Android java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by Chasty** [terrysahaidak/reanimated-gallery#4]
I just wanted to try it out with the new Reanimted 2 API and tested it on my android device and not working.
[https://i.imgur.com/B8Q4K7m.jpg](url)

**Comment by terrysahaidak** [comment]
Hi. Are you using a Xiaomi phone? Did you have such problems before? 
Worth to try to disable MIUI Optimization in developer settings.

Also, I recommend you to run from this commit on android
https://github.com/terrysahaidak/reanimated-gallery/commit/1e3ddc7ea57c01a14b6d8d951a62bfa263057a49
Just use `git checkout 1e3ddc7ea57c01a14b6d8d951a62bfa263057a49`

That's because currently, I use Reanimmated from Github because I use TS and there is no published version of Reanimated with TS support just yet.

**Comment by Chasty** [comment]
Yes, I'm using Xiaomi Red mi Note 5, I'm new to react native, and other
simple examples work well, thats the first time, tried to use reanimated 2

**Comment by terrysahaidak** [comment]
Well, then you should definitely check out MIUI Optimization in developer settings in your phone (you can turn it on back after successful launch).

Also, you should use this commit `1e3ddc7ea57c01a14b6d8d951a62bfa263057a49` until Reanimated team release a new version.

**Comment by Chasty** [comment]
Yeah it works now, and also I had to change my build.dradle file from com.android.tools.build:gradle:3.5.2  com.android.tools.build:gradle:3.6.3 👍
